image: maven:latest

stages:
  - build
  - test

# Cache downloaded dependencies and plugins between builds.
cache:
  paths:
    - .m2/repository  

build:
  stage: build
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - mvn test
